import { Command } from 'commander';

// ── All top-level commands (excluding hidden _loop) ─────────────────
const COMMANDS = [
  'init', 'launch', 'kill', 'status', 'dispatch', 'tail',
  'config', 'ui', 'plan', 'templates', 'merge', 'completion',
  'add', 'remove', 'logs', 'cost', 'resume',
];

// ── Commands that accept agent names as arguments ───────────────────
const AGENT_COMMANDS = ['launch', 'kill', 'dispatch', 'tail', 'merge', 'logs'];

// ── Global flags ────────────────────────────────────────────────────
const GLOBAL_FLAGS = ['--cwd', '--version', '--help'];

export function registerCompletionCommand(program: Command): void {
  program
    .command('completion <shell>')
    .description('Output shell completion script for bash, zsh, or fish')
    .addHelpText('after', `
Installation:

  bash:
    hive completion bash >> ~/.bashrc
    # or
    hive completion bash > /etc/bash_completion.d/hive

  zsh:
    hive completion zsh > "${"${"}fpath[1]}/_hive"
    # or add to ~/.zshrc:
    eval "$(hive completion zsh)"

  fish:
    hive completion fish > ~/.config/fish/completions/hive.fish
`)
    .action((shell: string) => {
      switch (shell) {
        case 'bash':
          console.log(bashCompletion());
          break;
        case 'zsh':
          console.log(zshCompletion());
          break;
        case 'fish':
          console.log(fishCompletion());
          break;
        default:
          console.error(
            `Unknown shell: "${shell}". Supported: bash, zsh, fish`,
          );
          process.exit(1);
      }
    });
}

// ── Agent name resolver (shared helper for all shells) ──────────────

function agentResolverBash(): string {
  return `
_hive_agents() {
  local agents
  if agents=$(hive config --agents --json 2>/dev/null); then
    echo "$agents" | grep -o '"name": *"[^"]*"' | sed 's/"name": *"//;s/"//'
  fi
}`;
}

function agentResolverZsh(): string {
  return `
_hive_agents() {
  local agents
  if agents=$(hive config --agents --json 2>/dev/null); then
    echo "$agents" | grep -o '"name": *"[^"]*"' | sed 's/"name": *"//;s/"//'
  fi
}`;
}

// ── Bash completion ─────────────────────────────────────────────────

function bashCompletion(): string {
  return `# hive bash completion — generated by hive completion bash
${agentResolverBash()}

_hive_completions() {
  local cur prev words cword
  _init_completion || return

  # Top-level: complete commands and global flags
  if [[ $cword -eq 1 ]]; then
    COMPREPLY=( $(compgen -W "${COMMANDS.join(' ')} ${GLOBAL_FLAGS.join(' ')}" -- "$cur") )
    return
  fi

  local cmd="\${words[1]}"

  # Dynamic agent completion for commands that accept agent names
  case "$cmd" in
    ${AGENT_COMMANDS.join('|')})
      local agents
      agents=$(_hive_agents)
      COMPREPLY=( $(compgen -W "$agents" -- "$cur") )
      return
      ;;
  esac

  # Per-command flag completion
  case "$cmd" in
    init)
      COMPREPLY=( $(compgen -W "--agents --preset --yes --templates --help" -- "$cur") )
      ;;
    launch)
      COMPREPLY=( $(compgen -W "--dry-run --attach --force --notify --no-notify --help" -- "$cur") )
      ;;
    kill)
      COMPREPLY=( $(compgen -W "--help" -- "$cur") )
      ;;
    status)
      COMPREPLY=( $(compgen -W "--json --watch --interval --help" -- "$cur") )
      ;;
    dispatch)
      COMPREPLY=( $(compgen -W "--from --type --help" -- "$cur") )
      ;;
    tail)
      COMPREPLY=( $(compgen -W "-n --last -f --follow --type --raw --notify --no-notify --help" -- "$cur") )
      ;;
    config)
      COMPREPLY=( $(compgen -W "--raw --json --agents --help" -- "$cur") )
      ;;
    merge)
      COMPREPLY=( $(compgen -W "--dry-run --continue --help" -- "$cur") )
      ;;
    completion)
      COMPREPLY=( $(compgen -W "bash zsh fish" -- "$cur") )
      ;;
    plan)
      COMPREPLY=( $(compgen -W "add ready dispatch import export graph update remove reset tree stats --json --compact --filter --help" -- "$cur") )
      ;;
    templates)
      COMPREPLY=( $(compgen -W "list show install diff --dir --help" -- "$cur") )
      ;;
    add)
      COMPREPLY=( $(compgen -W "--agent --poll --budget --daily-max --description --help" -- "$cur") )
      ;;
    remove)
      local agents
      agents=$(_hive_agents)
      COMPREPLY=( $(compgen -W "$agents --force --delete-branch --help" -- "$cur") )
      ;;
    logs)
      local agents
      agents=$(_hive_agents)
      COMPREPLY=( $(compgen -W "$agents -n --last -l --list -s --session -f --follow --json --help" -- "$cur") )
      ;;
    cost)
      COMPREPLY=( $(compgen -W "--agent --since --json --help" -- "$cur") )
      ;;
    resume)
      COMPREPLY=( $(compgen -W "--yes --force --dry-run --help" -- "$cur") )
      ;;
  esac
}

complete -F _hive_completions hive`;
}

// ── Zsh completion ──────────────────────────────────────────────────

function zshCompletion(): string {
  return `#compdef hive
# hive zsh completion — generated by hive completion zsh
${agentResolverZsh()}

_hive() {
  local -a commands global_flags

  commands=(
    'init:Initialize AgentHive in the current git repository'
    'launch:Start agent polling daemons in a tmux session'
    'kill:Stop agent daemons'
    'status:Show the state of all agents'
    'dispatch:Send a message to an agent via the chat file'
    'tail:Show agent coordination messages from the chat file'
    'config:Show the resolved configuration'
    'ui:Launch the interactive terminal dashboard'
    'plan:Manage the task plan'
    'templates:Manage agent prompt templates'
    'merge:Rebase agent branches onto main and push in order'
    'completion:Output shell completion script'
    'add:Add a new agent to the hive'
    'remove:Remove an agent from the hive'
    'logs:Show Claude Code transcript events'
    'cost:Show per-agent and aggregate cost summary'
    'resume:Detect orphaned state and relaunch dead agents'
  )

  global_flags=(
    '--cwd[Override working directory]:directory:_directories'
    '--version[Show version]'
    '--help[Show help]'
  )

  if (( CURRENT == 2 )); then
    _describe 'command' commands
    _arguments $global_flags
    return
  fi

  local cmd=\${words[2]}

  case "$cmd" in
    launch|kill|dispatch|tail|merge|logs)
      local -a agents
      agents=(\${(f)"$(_hive_agents)"})
      case "$cmd" in
        launch)
          _arguments \\
            '--dry-run[Show what would be launched]' \\
            '--attach[Attach to tmux session after launching]' \\
            '--force[Kill existing session before launching]' \\
            '--notify[Enable desktop notifications]' \\
            '--no-notify[Disable desktop notifications]' \\
            '*:agent:compadd -a agents'
          ;;
        kill)
          _arguments '*:agent:compadd -a agents'
          ;;
        dispatch)
          _arguments \\
            '--from[Sender role tag]:role:' \\
            '--type[Message type]:type:(REQUEST STATUS DONE QUESTION BLOCKER ACK WARN)' \\
            '1:target:compadd -a agents' \\
            '2:message:'
          ;;
        tail)
          _arguments \\
            '-n[Show last N messages]:count:' \\
            '--last[Show last N messages]:count:' \\
            '-f[Live follow mode]' \\
            '--follow[Live follow mode]' \\
            '--type[Filter by message type]:types:' \\
            '--raw[Show raw lines without color]' \\
            '--notify[Enable desktop notifications]' \\
            '--no-notify[Disable desktop notifications]' \\
            '1:agent:compadd -a agents'
          ;;
        merge)
          _arguments \\
            '--dry-run[Show what would be merged]' \\
            '--continue[Resume after resolved conflict]' \\
            '*:agent:compadd -a agents'
          ;;
        logs)
          _arguments \\
            '-n[Show last N events]:count:' \\
            '--last[Show last N events]:count:' \\
            '-l[List all sessions]' \\
            '--list[List all sessions]' \\
            '-s[Show specific session]:session_id:' \\
            '--session[Show specific session]:session_id:' \\
            '-f[Live-tail transcripts]' \\
            '--follow[Live-tail transcripts]' \\
            '--json[Output as JSON]' \\
            '1:agent:compadd -a agents'
          ;;
      esac
      ;;
    init)
      _arguments \\
        '--agents[Comma-separated agent names]:agents:' \\
        '--preset[Use a predefined agent set]:preset:(fullstack backend-only minimal)' \\
        '--yes[Skip interactive prompts]' \\
        '--templates[Install agent prompt templates]:value:'
      ;;
    status)
      _arguments \
        '--json[Output as JSON]' \
        '--watch[Continuously monitor agent health]' \
        '--interval[Watch interval in seconds]:seconds:'
      ;;
    config)
      _arguments \\
        '--raw[Show raw config.yaml]' \\
        '--json[Output as JSON]' \\
        '--agents[Show only resolved agents table]'
      ;;
    completion)
      _arguments '1:shell:(bash zsh fish)'
      ;;
    plan)
      local -a subcommands
      subcommands=(
        'add:Add a task to the plan'
        'ready:Show ready tasks'
        'dispatch:Dispatch ready tasks to agents'
        'import:Import a plan from file'
        'export:Export the plan to file'
        'graph:Show dependency graph'
        'update:Update a task'
        'remove:Remove a task'
        'reset:Reset a task'
        'tree:Show task tree'
        'stats:Show plan statistics'
      )
      _arguments \\
        '--json[Output as JSON]' \\
        '--compact[Compact view]' \\
        '--filter[Filter by agent, status, or label]:filter:' \\
        '1:subcommand:_describe "subcommand" subcommands'
      ;;
    templates)
      local -a subcommands
      subcommands=(
        'list:List available templates'
        'show:Show template contents'
        'install:Install templates'
        'diff:Show template differences'
      )
      _arguments \\
        '--dir[Template directory]:directory:_directories' \\
        '1:subcommand:_describe "subcommand" subcommands'
      ;;
    add)
      _arguments \\
        '--agent[Agent definition file name]:file:' \\
        '--poll[Poll interval in seconds]:seconds:' \\
        '--budget[Max USD per task]:usd:' \\
        '--daily-max[Max USD per day]:usd:' \\
        '--description[Agent description]:text:' \\
        '1:name:'
      ;;
    remove)
      local -a agents
      agents=(\${(f)"$(_hive_agents)"})
      _arguments \\
        '--force[Remove even if running]' \\
        '--delete-branch[Delete the git branch]' \\
        '1:agent:compadd -a agents'
      ;;
    cost)
      local -a agents
      agents=(\${(f)"$(_hive_agents)"})
      _arguments \\
        '--agent[Show breakdown for one agent]:agent:compadd -a agents' \\
        '--since[Filter by date (YYYY-MM-DD)]:date:' \\
        '--json[Output as JSON]'
      ;;
    resume)
      _arguments \\
        '--yes[Skip confirmation prompt]' \\
        '--force[Restart even running agents]' \\
        '--dry-run[Show recovery plan without executing]'
      ;;
  esac
}

_hive "$@"`;
}

// ── Fish completion ─────────────────────────────────────────────────

function fishCompletion(): string {
  const lines: string[] = [
    '# hive fish completion — generated by hive completion fish',
    '',
    '# Helper to get agent names from config',
    'function __hive_agents',
    '  hive config --agents --json 2>/dev/null | string match -r \'"name": *"([^"]*)\"\' | string replace -r \'"name": *"([^"]*)\"\' \'$1\'',
    'end',
    '',
    '# Detect if a subcommand has been given',
    'function __hive_no_subcommand',
    '  set -l cmd (commandline -opc)',
    '  for c in init launch kill status dispatch tail config ui plan templates merge completion add remove logs cost resume',
    '    if contains -- $c $cmd',
    '      return 1',
    '    end',
    '  end',
    '  return 0',
    'end',
    '',
    '# Detect current subcommand',
    'function __hive_using_subcommand',
    '  set -l cmd (commandline -opc)',
    '  contains -- $argv[1] $cmd',
    'end',
    '',
    '# Global flags',
    'complete -c hive -n __hive_no_subcommand -l cwd -d "Override working directory" -rF',
    'complete -c hive -n __hive_no_subcommand -l version -d "Show version"',
    'complete -c hive -n __hive_no_subcommand -l help -d "Show help"',
    '',
    '# Commands',
  ];

  const commandDescs: Record<string, string> = {
    init: 'Initialize AgentHive in the current git repository',
    launch: 'Start agent polling daemons in a tmux session',
    kill: 'Stop agent daemons',
    status: 'Show the state of all agents',
    dispatch: 'Send a message to an agent via the chat file',
    tail: 'Show agent coordination messages from the chat file',
    config: 'Show the resolved configuration',
    ui: 'Launch the interactive terminal dashboard',
    plan: 'Manage the task plan',
    templates: 'Manage agent prompt templates',
    merge: 'Rebase agent branches onto main and push in order',
    completion: 'Output shell completion script',
    add: 'Add a new agent to the hive',
    remove: 'Remove an agent from the hive',
    logs: 'Show Claude Code transcript events',
    cost: 'Show per-agent and aggregate cost summary',
    resume: 'Detect orphaned state and relaunch dead agents',
  };

  for (const [cmd, desc] of Object.entries(commandDescs)) {
    lines.push(`complete -c hive -n __hive_no_subcommand -a ${cmd} -d "${desc}"`);
  }

  lines.push('');
  lines.push('# init options');
  lines.push('complete -c hive -n "__hive_using_subcommand init" -l agents -d "Comma-separated agent names"');
  lines.push('complete -c hive -n "__hive_using_subcommand init" -l preset -d "Use predefined agent set" -a "fullstack backend-only minimal"');
  lines.push('complete -c hive -n "__hive_using_subcommand init" -l yes -d "Skip interactive prompts"');
  lines.push('complete -c hive -n "__hive_using_subcommand init" -l templates -d "Install agent prompt templates"');

  lines.push('');
  lines.push('# launch options + agent names');
  lines.push('complete -c hive -n "__hive_using_subcommand launch" -l dry-run -d "Show what would be launched"');
  lines.push('complete -c hive -n "__hive_using_subcommand launch" -l attach -d "Attach to tmux session"');
  lines.push('complete -c hive -n "__hive_using_subcommand launch" -l force -d "Kill existing session"');
  lines.push('complete -c hive -n "__hive_using_subcommand launch" -l notify -d "Enable notifications"');
  lines.push('complete -c hive -n "__hive_using_subcommand launch" -l no-notify -d "Disable notifications"');
  lines.push('complete -c hive -n "__hive_using_subcommand launch" -a "(__hive_agents)" -d "Agent name"');

  lines.push('');
  lines.push('# kill — agent names');
  lines.push('complete -c hive -n "__hive_using_subcommand kill" -a "(__hive_agents)" -d "Agent name"');

  lines.push('');
  lines.push('# status options');
  lines.push('complete -c hive -n "__hive_using_subcommand status" -l json -d "Output as JSON"');
  lines.push('complete -c hive -n "__hive_using_subcommand status" -l watch -d "Continuously monitor agent health"');
  lines.push('complete -c hive -n "__hive_using_subcommand status" -l interval -d "Watch interval in seconds" -r');

  lines.push('');
  lines.push('# dispatch — agent names + options');
  lines.push('complete -c hive -n "__hive_using_subcommand dispatch" -a "(__hive_agents)" -d "Target agent"');
  lines.push('complete -c hive -n "__hive_using_subcommand dispatch" -l from -d "Sender role tag"');
  lines.push('complete -c hive -n "__hive_using_subcommand dispatch" -l type -d "Message type" -a "REQUEST STATUS DONE QUESTION BLOCKER ACK WARN"');

  lines.push('');
  lines.push('# tail — agent names + options');
  lines.push('complete -c hive -n "__hive_using_subcommand tail" -a "(__hive_agents)" -d "Agent name"');
  lines.push('complete -c hive -n "__hive_using_subcommand tail" -s n -l last -d "Show last N messages"');
  lines.push('complete -c hive -n "__hive_using_subcommand tail" -s f -l follow -d "Live follow mode"');
  lines.push('complete -c hive -n "__hive_using_subcommand tail" -l type -d "Filter by message type"');
  lines.push('complete -c hive -n "__hive_using_subcommand tail" -l raw -d "Show raw lines"');
  lines.push('complete -c hive -n "__hive_using_subcommand tail" -l notify -d "Enable notifications"');
  lines.push('complete -c hive -n "__hive_using_subcommand tail" -l no-notify -d "Disable notifications"');

  lines.push('');
  lines.push('# config options');
  lines.push('complete -c hive -n "__hive_using_subcommand config" -l raw -d "Show raw config.yaml"');
  lines.push('complete -c hive -n "__hive_using_subcommand config" -l json -d "Output as JSON"');
  lines.push('complete -c hive -n "__hive_using_subcommand config" -l agents -d "Show resolved agents table"');

  lines.push('');
  lines.push('# merge — agent names + options');
  lines.push('complete -c hive -n "__hive_using_subcommand merge" -a "(__hive_agents)" -d "Agent name"');
  lines.push('complete -c hive -n "__hive_using_subcommand merge" -l dry-run -d "Show what would be merged"');
  lines.push('complete -c hive -n "__hive_using_subcommand merge" -l continue -d "Resume after resolved conflict"');

  lines.push('');
  lines.push('# completion — shell names');
  lines.push('complete -c hive -n "__hive_using_subcommand completion" -a "bash zsh fish" -d "Shell type"');

  lines.push('');
  lines.push('# plan subcommands');
  lines.push('complete -c hive -n "__hive_using_subcommand plan" -a "add ready dispatch import export graph update remove reset tree stats" -d "Plan subcommand"');
  lines.push('complete -c hive -n "__hive_using_subcommand plan" -l json -d "Output as JSON"');
  lines.push('complete -c hive -n "__hive_using_subcommand plan" -l compact -d "Compact view"');
  lines.push('complete -c hive -n "__hive_using_subcommand plan" -l filter -d "Filter by agent, status, or label"');

  lines.push('');
  lines.push('# templates subcommands');
  lines.push('complete -c hive -n "__hive_using_subcommand templates" -a "list show install diff" -d "Templates subcommand"');
  lines.push('complete -c hive -n "__hive_using_subcommand templates" -l dir -d "Template directory"');

  lines.push('');
  lines.push('# add options');
  lines.push('complete -c hive -n "__hive_using_subcommand add" -l agent -d "Agent definition file name"');
  lines.push('complete -c hive -n "__hive_using_subcommand add" -l poll -d "Poll interval in seconds"');
  lines.push('complete -c hive -n "__hive_using_subcommand add" -l budget -d "Max USD per task"');
  lines.push('complete -c hive -n "__hive_using_subcommand add" -l daily-max -d "Max USD per day"');
  lines.push('complete -c hive -n "__hive_using_subcommand add" -l description -d "Agent description"');

  lines.push('');
  lines.push('# remove — agent names + options');
  lines.push('complete -c hive -n "__hive_using_subcommand remove" -a "(__hive_agents)" -d "Agent name"');
  lines.push('complete -c hive -n "__hive_using_subcommand remove" -l force -d "Remove even if running"');
  lines.push('complete -c hive -n "__hive_using_subcommand remove" -l delete-branch -d "Delete the git branch"');

  lines.push('');
  lines.push('# logs — agent names + options');
  lines.push('complete -c hive -n "__hive_using_subcommand logs" -a "(__hive_agents)" -d "Agent name"');
  lines.push('complete -c hive -n "__hive_using_subcommand logs" -s n -l last -d "Show last N events"');
  lines.push('complete -c hive -n "__hive_using_subcommand logs" -s l -l list -d "List all sessions"');
  lines.push('complete -c hive -n "__hive_using_subcommand logs" -s s -l session -d "Show specific session"');
  lines.push('complete -c hive -n "__hive_using_subcommand logs" -s f -l follow -d "Live-tail transcripts"');
  lines.push('complete -c hive -n "__hive_using_subcommand logs" -l json -d "Output as JSON"');

  lines.push('');
  lines.push('# cost options');
  lines.push('complete -c hive -n "__hive_using_subcommand cost" -l agent -d "Show breakdown for one agent"');
  lines.push('complete -c hive -n "__hive_using_subcommand cost" -l since -d "Filter by date (YYYY-MM-DD)"');
  lines.push('complete -c hive -n "__hive_using_subcommand cost" -l json -d "Output as JSON"');

  lines.push('');
  lines.push('# resume options');
  lines.push('complete -c hive -n "__hive_using_subcommand resume" -l yes -d "Skip confirmation prompt"');
  lines.push('complete -c hive -n "__hive_using_subcommand resume" -l force -d "Restart even running agents"');
  lines.push('complete -c hive -n "__hive_using_subcommand resume" -l dry-run -d "Show recovery plan without executing"');

  lines.push('');

  return lines.join('\n');
}
